In [1]:
import torch
from torch import nn

In [14]:
class NeuralNetwork(nn.Module):
    def __init__(self,input):
        super(NeuralNetwork, self).__init__()
        self.linear =  nn.Linear(input,1)

    def forward(self, x):
        y = torch.sigmoid(self.linear(x))
        return y

model = NeuralNetwork(6)
print(model)

NeuralNetwork(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)


In [15]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.3216,  0.1764, -0.2877,  0.0224,  0.0876, -0.1029]],
       requires_grad=True)
Parameter containing:
tensor([-0.3901], requires_grad=True)


In [5]:
file = 'model.pth'
torch.save(model,file)

In [9]:
model_load = torch.load(file)
model_load.eval()

NeuralNetwork(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [10]:
for param in model_load.parameters():
    print(param)

Parameter containing:
tensor([[ 0.0359, -0.1966,  0.2582, -0.0995,  0.1117, -0.2410]],
       requires_grad=True)
Parameter containing:
tensor([-0.0774], requires_grad=True)


In [16]:
# 仅保存参数
torch.save(model.state_dict(),file)

In [17]:
model_load= NeuralNetwork(6)
model_load.load_state_dict(torch.load(file))
model_load.eval()

NeuralNetwork(
  (linear): Linear(in_features=6, out_features=1, bias=True)
)

In [18]:
for param in model_load.parameters():
    print(param)

Parameter containing:
tensor([[ 0.3216,  0.1764, -0.2877,  0.0224,  0.0876, -0.1029]],
       requires_grad=True)
Parameter containing:
tensor([-0.3901], requires_grad=True)


In [19]:
model.state_dict()

OrderedDict([('linear.weight',
              tensor([[ 0.3216,  0.1764, -0.2877,  0.0224,  0.0876, -0.1029]])),
             ('linear.bias', tensor([-0.3901]))])

**设置checkpoint**

In [22]:
model = NeuralNetwork(6)
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

checkpoint = {
    "epoch":50,
    "model_state":model.state_dict(),
    "optim_state":optimizer.state_dict()
}

In [23]:
torch.save(checkpoint,"checkpoint.pth")

In [25]:
model_resume = model = NeuralNetwork(6)
optimizer_resume = torch.optim.SGD(model_resume.parameters(),lr=0)

load_checkpoint = torch.load("checkpoint.pth")
epoch = load_checkpoint['epoch']
model_resume.load_state_dict(load_checkpoint['model_state'])
optimizer_resume.load_state_dict(load_checkpoint['optim_state'])